-- =====================================================================
--  BAGAÚSTE BAR — Dados do menu (seed)
--  Execute DEPOIS do schema.sql, no SQL Editor do Supabase.
--  Recarrega o menu do zero (apaga o que existir e volta a inserir).
-- =====================================================================

begin;
delete from public.products;
delete from public.categories;

-- Petiscos Quentes
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Petiscos Quentes', 'Hot Snacks', 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Pataniscas de bacalhau', 'Cod fritters', '', '', 6.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Feijoada de feijocas', 'Butter-bean stew', '', '', 5.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Amêijoas à Bulhão Pato', 'Clams Bulhão Pato', '', '', 10.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Gambas ao alho', 'Garlic prawns', '', '', 10.00, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Ovos rotos com presunto', 'Broken eggs with cured ham', '', '', 9.00, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Pica-pau', 'Pica-pau (sautéed beef bites)', '', '', 9.00, 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Cogumelos salteados com bacon', 'Sautéed mushrooms with bacon', '', '', 6.00, 7, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Rojões', 'Rojões (fried pork bites)', '', '', 6.00, 8, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Mini bruschettas quentes (6 un.)', 'Warm mini bruschettas (6 pcs)', '', '', 5.00, 9, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Moelas', 'Braised gizzards', '', '', 6.00, 10, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Batatas fritas', 'French fries', '', '', 2.50, 11, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Prego', 'Steak sandwich (prego)', '', '', 5.00, 12, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Quentes' limit 1), 'Mini pregos de vazia ou picanha (6 un.)', 'Mini steak sandwiches, sirloin or picanha (6 pcs)', '', '', 14.00, 13, true);

-- Petiscos Frios
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Petiscos Frios', 'Cold Snacks', 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Frios' limit 1), 'Camarão cozido com molho de pimentas e cocktail', 'Boiled shrimp with pepper & cocktail sauce', '', '', 10.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Frios' limit 1), 'Salmão fumado com queijo fresco', 'Smoked salmon with fresh cheese', '', '', 10.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Frios' limit 1), 'Mix de patés e azeites', 'Pâté & olive oil selection', '', '', 5.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Frios' limit 1), 'Polvo à galega', 'Galician-style octopus', '', '', 15.00, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Petiscos Frios' limit 1), 'Rissóis, bolinhos de bacalhau e croquetes (6 un.)', 'Rissoles, cod cakes & croquettes (6 pcs)', '', '', 6.00, 5, true);

-- Saladas
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Saladas', 'Salads', 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Saladas' limit 1), 'Salada de feijão-frade com atum', 'Black-eyed pea salad with tuna', '', '', 5.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Saladas' limit 1), 'Salada de bacalhau com grão-de-bico', 'Cod salad with chickpeas', '', '', 6.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Saladas' limit 1), 'Salada mista', 'Mixed salad', '', '', 4.00, 3, true);

-- Omeletes
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Omeletes', 'Omelettes', 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Omeletes' limit 1), 'Omelete de queijo e fiambre', 'Cheese & ham omelette', '', '', 4.50, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Omeletes' limit 1), 'Omelete de salpicão', 'Salpicão (smoked pork) omelette', '', '', 4.50, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Omeletes' limit 1), 'Omelete de cebola', 'Onion omelette', '', '', 4.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Omeletes' limit 1), 'Omelete vegetariana', 'Vegetarian omelette', '', '', 4.00, 4, true);

-- Tostas & Sanduíches
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Tostas & Sanduíches', 'Toasts & Sandwiches', 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tostas & Sanduíches' limit 1), 'Torrada tradicional', 'Traditional buttered toast', '', '', 2.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tostas & Sanduíches' limit 1), 'Torrada com pão de centeio', 'Rye bread toast', '', '', 3.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tostas & Sanduíches' limit 1), 'Tosta mista em pão de centeio', 'Ham & cheese toastie on rye', 'Com azeite e orégãos.', 'With olive oil and oregano.', 4.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tostas & Sanduíches' limit 1), 'Pão de alho', 'Garlic bread', '', '', 4.00, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tostas & Sanduíches' limit 1), 'Sanduíche de atum ou delícias do mar', 'Tuna or crab-stick sandwich', '', '', 4.00, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tostas & Sanduíches' limit 1), 'Sanduíche de cogumelos e pimentos', 'Mushroom & pepper sandwich', '', '', 4.00, 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tostas & Sanduíches' limit 1), 'Cachorro', 'Hot dog', '', '', 7.00, 7, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tostas & Sanduíches' limit 1), 'Cachorro (1 metro)', 'Hot dog (1 metre)', '', '', 15.00, 8, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tostas & Sanduíches' limit 1), 'Baguete de presunto com queijo amanteigado', 'Cured ham baguette with creamy cheese', '', '', 12.00, 9, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tostas & Sanduíches' limit 1), 'Folhado recheado', 'Filled puff pastry', '', '', 12.00, 10, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tostas & Sanduíches' limit 1), 'Folhado recheado vegetariano', 'Vegetarian filled puff pastry', '', '', 12.00, 11, true);

-- Tábuas
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Tábuas', 'Sharing Boards', 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tábuas' limit 1), 'Tábua mista', 'Mixed board', 'Enchidos e queijos.', 'Cured meats & cheeses.', 14.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tábuas' limit 1), 'Tábua de enchidos', 'Cured sausage board', '', '', 14.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Tábuas' limit 1), 'Tábua de fumeiros tradicionais', 'Traditional smoked meats board', '', '', 14.00, 3, true);

-- Menus (por pessoa)
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Menus (por pessoa)', 'Set Menus (per person)', 7, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Menus (por pessoa)' limit 1), 'ALL IN – Menu de Petiscos', 'ALL IN – Snacks Menu', '7 petiscos, prato quente de carnes grelhadas, sobremesa, água ou sangria leve ou vinho ou cerveja de pressão, café.', '7 snacks, a hot grilled-meat dish, dessert, water or light sangria or wine or draught beer, coffee.', 25.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Menus (por pessoa)' limit 1), 'Cozido à Portuguesa', 'Portuguese boiled meats & vegetables', 'Sextas e sábados ao jantar, com reserva para grupos. Entradas, prato principal, sobremesa, água ou vinho, café.', 'Friday and Saturday dinner, group booking required. Starters, main course, dessert, water or wine, coffee.', 25.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Menus (por pessoa)' limit 1), 'Bacalhau Zé do Pipo', 'Cod Zé do Pipo', 'Sextas e sábados ao jantar, com reserva para grupos. Entradas, prato principal, sobremesa, água ou vinho, café.', 'Friday and Saturday dinner, group booking required. Starters, main course, dessert, water or wine, coffee.', 25.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Menus (por pessoa)' limit 1), 'Raclette – Serviço de Esplanada', 'Raclette – Terrace Service', 'Mix de carnes, vegetais e queijos, água ou sangria leve ou vinho ou cerveja de pressão, café.', 'A mix of meats, vegetables and cheeses, water or light sangria or wine or draught beer, coffee.', 25.00, 4, true);

-- Sobremesas
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Sobremesas', 'Desserts', 8, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sobremesas' limit 1), 'Pudim', 'Crème caramel', '', '', 3.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sobremesas' limit 1), 'Rabanadas', 'Portuguese French toast', '', '', 3.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sobremesas' limit 1), 'Aletria', 'Sweet vermicelli pudding', '', '', 3.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sobremesas' limit 1), 'Requeijão com doce de abóbora', 'Ricotta with pumpkin jam', '', '', 3.00, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sobremesas' limit 1), 'Romeu e Julieta', 'Cheese with quince jam', '', '', 3.00, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sobremesas' limit 1), 'Tarte de maçã', 'Apple tart', '', '', 3.00, 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sobremesas' limit 1), 'Folhado de maçã com bola de gelado', 'Apple pastry with a scoop of ice cream', '', '', 4.00, 7, true);

-- Confeitaria & Gelataria
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Confeitaria & Gelataria', 'Pastry & Ice Cream', 9, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Bolo de chocolate', 'Chocolate cake', 'Fatia (bolo inteiro 20€).', 'Slice (whole cake €20).', 2.50, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Bolo artesanal', 'Homemade cake', 'Fatia (bolo inteiro 16€).', 'Slice (whole cake €16).', 2.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Bolachas artesanais', 'Homemade cookies', 'Unidade (caixa 16€).', 'Each (box €16).', 0.90, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Covilhetes', 'Covilhete (savoury pastry)', 'Mini (normal 1,50€).', 'Mini (regular €1.50).', 0.90, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Cristas', 'Crista (puff pastry)', 'Mini (normal 1,50€).', 'Mini (regular €1.50).', 0.90, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Häagen-Dazs – Mini Cup', 'Häagen-Dazs – Mini Cup', '', '', 2.95, 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Häagen-Dazs – Pint', 'Häagen-Dazs – Pint', '', '', 7.79, 7, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Gelado de copo – 1 bola', 'Ice cream cup – 1 scoop', '', '', 2.00, 8, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Gelado de copo – 2 bolas', 'Ice cream cup – 2 scoops', '', '', 3.00, 9, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Macadamia Crunch', 'Macadamia Crunch', 'Quatro meias bolas de Cookies & Cream, com molho de chocolate fundido, um toque de chantilly e bolachas de chocolate.', 'Four half-scoops of Cookies & Cream with melted chocolate sauce, a touch of whipped cream and chocolate cookies.', 6.00, 10, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Caramel Crunch', 'Caramel Crunch', 'Quatro meias bolas de Macadamia Nut Brittle, pedaços de bolacha, nozes de macadâmia, molho de caramelo e chantilly.', 'Four half-scoops of Macadamia Nut Brittle, cookie pieces, macadamia nuts, caramel sauce and whipped cream.', 6.00, 11, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Cookie Crunch', 'Cookie Crunch', 'Um brownie de chocolate suave entre uma bola de Belgian Chocolate e uma de Vanilla Caramel Brownie, banhadas em chocolate fundido e avelãs caramelizadas.', 'A soft chocolate brownie between a scoop of Belgian Chocolate and one of Vanilla Caramel Brownie, coated in melted chocolate and caramelised hazelnuts.', 6.00, 12, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Brownie Explosion', 'Brownie Explosion', 'Duas meias bolas de Salted Caramel e de Vanilla com bolachas Speculoos crocantes, natas e molho de caramelo.', 'Two half-scoops of Salted Caramel and Vanilla with crunchy Speculoos biscuits, cream and caramel sauce.', 6.00, 13, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Banana Chocolate Crepe', 'Banana Chocolate Crepe', 'Um crepe com uma bola de Vanilla Caramel Brownie e outra de Chocolate & Hazelnut, pedaços de brownie, rodelas de banana, avelãs caramelizadas, natas e molho de chocolate fundido.', 'A crepe with a scoop of Vanilla Caramel Brownie and one of Chocolate & Hazelnut, brownie pieces, banana slices, caramelised hazelnuts, cream and melted chocolate sauce.', 7.00, 14, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Petit Gâteau e gelado', 'Petit Gâteau with ice cream', 'Bolo de chocolate servido quente, com coração de chocolate derretido, natas, raspas de chocolate e uma bola de gelado à escolha.', 'Warm chocolate cake with a molten chocolate centre, cream, chocolate shavings and a scoop of ice cream of your choice.', 7.00, 15, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Ice Cream Coffee', 'Ice Cream Coffee', 'Uma bola de gelado de baunilha com café frio e molho de chocolate fundido, chantilly e cacau em pó.', 'A scoop of vanilla ice cream with cold coffee and melted chocolate sauce, whipped cream and cocoa powder.', 4.00, 16, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Confeitaria & Gelataria' limit 1), 'Fondue com gelado e frutas', 'Ice cream & fruit fondue', 'Escolha entre molho de chocolate negro ou de leite, com 12 mini bolas de gelado. Servido com frutas da época, pastelaria e um topping.', 'Choose dark or milk chocolate sauce, with 12 mini scoops of ice cream. Served with seasonal fruit, pastries and a topping.', 20.00, 17, true);

-- Cafés & Chás
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Cafés & Chás', 'Coffee & Tea', 10, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cafés & Chás' limit 1), 'Café expresso', 'Espresso', '', '', 1.20, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cafés & Chás' limit 1), 'Pingo', 'Espresso with a dash of milk', '', '', 1.20, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cafés & Chás' limit 1), 'Abatanado', 'Americano', '', '', 1.20, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cafés & Chás' limit 1), 'Carioca', 'Weak espresso (carioca)', '', '', 1.20, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cafés & Chás' limit 1), 'Café duplo', 'Double espresso', '', '', 1.60, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cafés & Chás' limit 1), 'Descafeinado', 'Decaf coffee', '', '', 1.20, 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cafés & Chás' limit 1), 'Cappuccino', 'Cappuccino', '', '', 1.80, 7, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cafés & Chás' limit 1), 'Galão / Meia de leite', 'Galão (milky coffee)', '', '', 1.80, 8, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cafés & Chás' limit 1), 'Chá (saqueta, preto ou verde)', 'Tea (bag, black or green)', '', '', 2.00, 9, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cafés & Chás' limit 1), 'Infusões (camomila, cidreira, outros)', 'Herbal infusions (chamomile, lemon balm, others)', '', '', 2.00, 10, true);

-- Sumos, Águas & Refrigerantes
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Sumos, Águas & Refrigerantes', 'Juices, Water & Soft Drinks', 11, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Sumo de laranja natural', 'Fresh orange juice', '', '', 3.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Néctar Compal', 'Compal fruit nectar', '', '', 2.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Limonada', 'Lemonade', '', '', 2.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Sumo de frutos vermelhos (copo)', 'Red berry juice (glass)', '', '', 3.00, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Água mineral', 'Still mineral water', '', '', 1.50, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Água com gás', 'Sparkling water', '', '', 1.50, 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Água com sabores', 'Flavoured water', '', '', 1.50, 7, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Red Bull', 'Red Bull', '', '', 2.50, 8, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), '7up', '7up', '', '', 1.80, 9, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Coca-Cola / Coca-Cola Zero', 'Coca-Cola / Coca-Cola Zero', '', '', 1.80, 10, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Ice tea', 'Iced tea', '', '', 1.80, 11, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Sumol / Fanta', 'Sumol / Fanta', '', '', 1.80, 12, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Guaraná', 'Guaraná', '', '', 1.80, 13, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Sumos, Águas & Refrigerantes' limit 1), 'Leite achocolatado UCAL', 'UCAL chocolate milk', '', '', 1.80, 14, true);

-- Cervejas
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Cervejas', 'Beers', 12, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'San Miguel sem álcool', 'San Miguel alcohol-free', 'Garrafa.', 'Bottle.', 2.50, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Alhambra Reserva 1925 (330 ml)', 'Alhambra Reserva 1925 (330 ml)', '', '', 3.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Corona (35,5 cl)', 'Corona (35.5 cl)', '', '', 3.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Bud (33 cl)', 'Bud (33 cl)', '', '', 3.00, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Becks (27,5 cl)', 'Becks (27.5 cl)', '', '', 3.00, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), '1906 Reserva Especial', '1906 Reserva Especial', '', '', 3.00, 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), '1906 Red Vintage', '1906 Red Vintage', '', '', 3.00, 7, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Löwenbräu (33 cl)', 'Löwenbräu (33 cl)', '', '', 4.00, 8, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Leffe (33 cl)', 'Leffe (33 cl)', '', '', 4.00, 9, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Stella (33 cl)', 'Stella (33 cl)', '', '', 4.00, 10, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Hoegaarden (33 cl)', 'Hoegaarden (33 cl)', '', '', 5.00, 11, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Alhambra Reserva 1925 (700 ml)', 'Alhambra Reserva 1925 (700 ml)', '', '', 6.00, 12, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Franziskaner Weiss', 'Franziskaner Weiss', '', '', 6.00, 13, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Erdinger Urweisse', 'Erdinger Urweisse', '', '', 6.00, 14, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Erdinger Pikantus', 'Erdinger Pikantus', '', '', 7.00, 15, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Balde 10 minis – Sagres', 'Bucket of 10 minis – Sagres', '', '', 14.00, 16, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Balde 10 minis – Super Bock', 'Bucket of 10 minis – Super Bock', '', '', 14.00, 17, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Balde 10 minis – Coronita', 'Bucket of 10 minis – Coronita', '', '', 21.00, 18, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Bila Strong (33 cl)', 'Bila Strong (33 cl)', 'Cerveja artesanal.', 'Craft beer.', 4.00, 19, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Bila Stout', 'Bila Stout', 'Cerveja artesanal.', 'Craft beer.', 4.00, 20, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Bila Special (33 cl)', 'Bila Special (33 cl)', 'Cerveja artesanal.', 'Craft beer.', 4.00, 21, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Bila IPA', 'Bila IPA', 'Cerveja artesanal.', 'Craft beer.', 4.50, 22, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Bila Belgian Dark Strong Ale', 'Bila Belgian Dark Strong Ale', 'Cerveja artesanal.', 'Craft beer.', 6.00, 23, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Bila Special (750 ml)', 'Bila Special (750 ml)', 'Cerveja artesanal.', 'Craft beer.', 8.00, 24, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Bila Strong (750 ml)', 'Bila Strong (750 ml)', 'Cerveja artesanal.', 'Craft beer.', 8.00, 25, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Bila Stout (750 ml)', 'Bila Stout (750 ml)', 'Cerveja artesanal.', 'Craft beer.', 8.00, 26, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Somersby', 'Somersby', 'Cidra.', 'Cider.', 2.50, 27, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Pale Lager San Miguel (pressão)', 'Pale Lager San Miguel (draught)', 'Média 1,60€ · caneca 3,00€.', 'Small €1.60 · large €3.00.', 1.60, 28, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Maestra Dunkel / Preta (pressão)', 'Maestra Dunkel / Dark (draught)', 'Média 1,60€ · caneca 3,00€.', 'Small €1.60 · large €3.00.', 1.60, 29, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'IPA (pressão)', 'IPA (draught)', 'Média 1,60€ · caneca 3,00€.', 'Small €1.60 · large €3.00.', 1.60, 30, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Pale Lager San Miguel – a metro (XL)', 'Pale Lager San Miguel – the metre (XL)', '', '', 6.00, 31, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'Maestra Dunkel / Preta – a metro (XL)', 'Maestra Dunkel / Dark – the metre (XL)', '', '', 6.00, 32, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cervejas' limit 1), 'IPA – a metro (XL)', 'IPA – the metre (XL)', '', '', 6.00, 33, true);

-- Vinhos
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Vinhos', 'Wines', 13, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Douro Branco Reserva', 'Douro White Reserva', 'Copo.', 'Glass.', 3.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Douro Tinto Reserva', 'Douro Red Reserva', 'Copo.', 'Glass.', 3.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Douro Rosé', 'Douro Rosé', 'Copo.', 'Glass.', 3.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Verde Branco', 'Vinho Verde White', 'Copo.', 'Glass.', 3.00, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Ceira Branco (Douro)', 'Ceira White (Douro)', 'Garrafa.', 'Bottle.', 8.00, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Altar do Diabo Tinto', 'Altar do Diabo Red', 'Garrafa.', 'Bottle.', 8.00, 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Ceira Branco Reserva', 'Ceira White Reserva', 'Garrafa.', 'Bottle.', 12.00, 7, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Ceira Tinto Reserva', 'Ceira Red Reserva', 'Garrafa.', 'Bottle.', 12.00, 8, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Ceira Tinto Grande Reserva', 'Ceira Red Grande Reserva', 'Garrafa.', 'Bottle.', 20.00, 9, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Dona Augusta Verde', 'Dona Augusta Vinho Verde', 'Garrafa.', 'Bottle.', 8.00, 10, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Dona Augusta Douro DOC', 'Dona Augusta Douro DOC', 'Garrafa.', 'Bottle.', 9.00, 11, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Dona Augusta Douro Reserva', 'Dona Augusta Douro Reserva', 'Garrafa.', 'Bottle.', 11.00, 12, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Presidente Douro Branco Reserva', 'Presidente Douro White Reserva', 'Garrafa.', 'Bottle.', 12.00, 13, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Presidente Douro Tinto Reserva', 'Presidente Douro Red Reserva', 'Garrafa.', 'Bottle.', 12.00, 14, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Wine Please – Tinto Reserva Douro', 'Wine Please – Douro Red Reserva', 'Garrafa.', 'Bottle.', 15.00, 15, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Dona Augusta Grande Reserva Dão (Touriga Nacional)', 'Dona Augusta Grande Reserva Dão (Touriga Nacional)', 'Garrafa.', 'Bottle.', 24.00, 16, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Felgueiras Frisante Branco', 'Felgueiras Semi-sparkling White', 'Garrafa.', 'Bottle.', 9.00, 17, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Felgueiras Tinto', 'Felgueiras Red', 'Garrafa.', 'Bottle.', 9.00, 18, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Felgueiras Rosé', 'Felgueiras Rosé', 'Garrafa.', 'Bottle.', 9.00, 19, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Felgueiras Escolha Branco', 'Felgueiras Escolha White', 'Garrafa.', 'Bottle.', 10.00, 20, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Felgueiras Grande Escolha Branco', 'Felgueiras Grande Escolha White', 'Garrafa.', 'Bottle.', 12.00, 21, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Tojeira Grande Escolha Loureiro', 'Tojeira Grande Escolha Loureiro', 'Garrafa.', 'Bottle.', 12.00, 22, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Tojeira Azal', 'Tojeira Azal', 'Garrafa.', 'Bottle.', 12.00, 23, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Tojeira Rosé', 'Tojeira Rosé', 'Garrafa.', 'Bottle.', 12.00, 24, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Tojeira Alvarinho', 'Tojeira Alvarinho', 'Garrafa.', 'Bottle.', 15.00, 25, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Tojeira Alvarinho Trajadura', 'Tojeira Alvarinho Trajadura', 'Garrafa.', 'Bottle.', 15.00, 26, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Monte S. Sebastião Tinto Colheita', 'Monte S. Sebastião Red Colheita', 'Garrafa.', 'Bottle.', 13.00, 27, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Monte S. Sebastião Branco Colheita', 'Monte S. Sebastião White Colheita', 'Garrafa.', 'Bottle.', 13.00, 28, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Monte S. Sebastião Rosé Colheita', 'Monte S. Sebastião Rosé Colheita', 'Garrafa.', 'Bottle.', 13.00, 29, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Monte S. Sebastião Branco Reserva', 'Monte S. Sebastião White Reserva', 'Garrafa.', 'Bottle.', 22.00, 30, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Monte S. Sebastião Tinto Reserva', 'Monte S. Sebastião Red Reserva', 'Garrafa.', 'Bottle.', 22.00, 31, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Monte S. Sebastião Branco Grande Reserva', 'Monte S. Sebastião White Grande Reserva', 'Garrafa.', 'Bottle.', 30.00, 32, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinhos' limit 1), 'Monte S. Sebastião Tinto Grande Reserva', 'Monte S. Sebastião Red Grande Reserva', 'Garrafa.', 'Bottle.', 30.00, 33, true);

-- Vinho do Porto & Moscatel
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Vinho do Porto & Moscatel', 'Port & Muscatel', 14, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinho do Porto & Moscatel' limit 1), 'Moscatel', 'Moscatel', 'Copo.', 'Glass.', 3.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinho do Porto & Moscatel' limit 1), 'Porto Tawny', 'Tawny Port', 'Copo.', 'Glass.', 3.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinho do Porto & Moscatel' limit 1), 'Porto Tawny 10 anos', '10-year Tawny Port', 'Copo.', 'Glass.', 4.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinho do Porto & Moscatel' limit 1), 'Porto Branco', 'White Port', 'Copo.', 'Glass.', 3.00, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinho do Porto & Moscatel' limit 1), 'Porto Branco 10 anos', '10-year White Port', 'Copo.', 'Glass.', 4.00, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinho do Porto & Moscatel' limit 1), 'Porto Ruby', 'Ruby Port', 'Copo.', 'Glass.', 3.00, 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinho do Porto & Moscatel' limit 1), 'Porto LBV', 'LBV Port', 'Copo.', 'Glass.', 4.00, 7, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Vinho do Porto & Moscatel' limit 1), 'Porto Vintage', 'Vintage Port', 'Copo.', 'Glass.', 5.00, 8, true);

-- Espumantes & Sangrias
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Espumantes & Sangrias', 'Sparkling & Sangria', 15, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Espumantes & Sangrias' limit 1), 'Felgueiras Espumante Tinto', 'Felgueiras Sparkling Red', 'Garrafa.', 'Bottle.', 15.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Espumantes & Sangrias' limit 1), 'Felgueiras Espumante Branco', 'Felgueiras Sparkling White', 'Garrafa.', 'Bottle.', 15.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Espumantes & Sangrias' limit 1), 'Tojeira Espumante Branco', 'Tojeira Sparkling White', 'Garrafa.', 'Bottle.', 22.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Espumantes & Sangrias' limit 1), 'Sangria de frutos vermelhos (caneca)', 'Red berry sangria (jug)', '', '', 9.00, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Espumantes & Sangrias' limit 1), 'Sangria de frutos brancos (caneca)', 'White fruit sangria (jug)', '', '', 9.00, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Espumantes & Sangrias' limit 1), 'Sangria de espumante (caneca)', 'Sparkling sangria (jug)', '', '', 10.00, 6, true);

-- Mocktails
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Mocktails', 'Mocktails', 16, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Mocktails' limit 1), 'Blue Lagoon', 'Blue Lagoon', 'Curaçau, sprite, gelo, fatia de limão.', 'Curaçao, sprite, ice, lemon slice.', 4.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Mocktails' limit 1), 'Raspberry Lemonade', 'Raspberry Lemonade', 'Framboesas, limão, açúcar, água, gelo.', 'Raspberries, lemon, sugar, water, ice.', 4.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Mocktails' limit 1), 'Coconut Lemonade', 'Coconut Lemonade', 'Leite de coco, limão, açúcar, água, gelo.', 'Coconut milk, lemon, sugar, water, ice.', 4.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Mocktails' limit 1), 'Virgin Mojito', 'Virgin Mojito', 'Hortelã e limão macerados com açúcar, água com gás e gelo.', 'Mint and lime muddled with sugar, sparkling water and ice.', 4.00, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Mocktails' limit 1), 'Mango Orange Lemonade', 'Mango Orange Lemonade', 'Manga, laranja, limão, açúcar, água, gelo.', 'Mango, orange, lemon, sugar, water, ice.', 4.00, 5, true);

-- Cocktails
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Cocktails', 'Cocktails', 17, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Spritz Branco', 'White Spritz', 'Vinho branco, espumante, fatias de fruta, gelo.', 'White wine, sparkling wine, fruit slices, ice.', 5.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Clericot', 'Clericot', 'Vinho branco, frutas cortadas (maçã, pêra, morango, laranja), licor de laranja, gelo.', 'White wine, chopped fruit (apple, pear, strawberry, orange), orange liqueur, ice.', 4.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'White Wine Spritzer', 'White Wine Spritzer', 'Vinho branco, água com gás, gelo, fatia de limão ou lima.', 'White wine, sparkling water, ice, lemon or lime slice.', 3.50, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Tinto de Verano', 'Tinto de Verano', 'Vinho tinto leve, limonada, gelo, fatia de limão.', 'Light red wine, lemonade, ice, lemon slice.', 3.50, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Porto Spritz', 'Port Spritz', 'Porto branco, espumante, gelo, fatia de laranja.', 'White Port, sparkling wine, ice, orange slice.', 4.50, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Porto Tónico', 'Port & Tonic', 'Porto branco, água tónica, gelo, rodelas de laranja ou limão.', 'White Port, tonic water, ice, orange or lemon slices.', 5.00, 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Porto Mule', 'Port Mule', 'Porto Ruby, ginger beer, sumo de limão, gelo.', 'Ruby Port, ginger beer, lemon juice, ice.', 6.00, 7, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Porto Old Fashioned', 'Port Old Fashioned', 'Porto Tawny, bourbon, açúcar, bitter, gelo, casca de laranja.', 'Tawny Port, bourbon, sugar, bitters, ice, orange peel.', 8.00, 8, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Kir Royale', 'Kir Royale', 'Espumante, licor de cassis.', 'Sparkling wine, cassis liqueur.', 5.00, 9, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Mimosa', 'Mimosa', 'Espumante, sumo de laranja.', 'Sparkling wine, orange juice.', 5.00, 10, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Martini (Gin)', 'Martini (Gin)', 'Gin, vermute. 6€ / 7€ / 9€ conforme a marca.', 'Gin, vermouth. €6 / €7 / €9 by brand.', 6.00, 11, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Negroni', 'Negroni', 'Gin, Campari, vermute doce. 6€ / 7€ / 9€ conforme a marca.', 'Gin, Campari, sweet vermouth. €6 / €7 / €9 by brand.', 6.00, 12, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Gin Tónico', 'Gin & Tonic', 'Gin, água tónica, limão. 6€ / 7€ / 9€ conforme a marca.', 'Gin, tonic water, lemon. €6 / €7 / €9 by brand.', 6.00, 13, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Tom Collins', 'Tom Collins', 'Gin, sumo de limão, açúcar, água com gás. 6€ / 7€ / 9€ conforme a marca.', 'Gin, lemon juice, sugar, sparkling water. €6 / €7 / €9 by brand.', 6.00, 14, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Mint Julep', 'Mint Julep', 'Whisky, hortelã, açúcar. 5€ / 7€ / 10€ conforme a marca.', 'Whiskey, mint, sugar. €5 / €7 / €10 by brand.', 5.00, 15, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Manhattan', 'Manhattan', 'Rye whisky, vermute doce, bitter. 5€ / 7€ / 10€ conforme a marca.', 'Rye whiskey, sweet vermouth, bitters. €5 / €7 / €10 by brand.', 5.00, 16, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Whiskey Sour', 'Whiskey Sour', 'Whisky, sumo de limão, açúcar. 5€ / 7€ / 10€ conforme a marca.', 'Whiskey, lemon juice, sugar. €5 / €7 / €10 by brand.', 5.00, 17, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Moscow Mule', 'Moscow Mule', 'Vodka, ginger beer, sumo de limão. 5€ / 7€ conforme a marca.', 'Vodka, ginger beer, lemon juice. €5 / €7 by brand.', 5.00, 18, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Bloody Mary', 'Bloody Mary', 'Vodka, sumo de tomate, molho inglês, pimenta, sumo de limão. 5€ / 7€ conforme a marca.', 'Vodka, tomato juice, Worcestershire sauce, pepper, lemon juice. €5 / €7 by brand.', 5.00, 19, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Screwdriver', 'Screwdriver', 'Vodka, sumo de laranja. 5€ / 7€ conforme a marca.', 'Vodka, orange juice. €5 / €7 by brand.', 5.00, 20, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Daiquiri', 'Daiquiri', 'Rum branco, sumo de limão, açúcar. 5€ / 8€ conforme a marca.', 'White rum, lemon juice, sugar. €5 / €8 by brand.', 5.00, 21, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Mojito', 'Mojito', 'Rum branco, hortelã, açúcar, sumo de limão, água com gás. 5€ / 8€ conforme a marca.', 'White rum, mint, sugar, lemon juice, sparkling water. €5 / €8 by brand.', 5.00, 22, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Cuba Libre', 'Cuba Libre', 'Rum, cola, sumo de limão. 5€ / 8€ conforme a marca.', 'Rum, cola, lemon juice. €5 / €8 by brand.', 5.00, 23, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Piña Colada', 'Piña Colada', 'Rum, creme de coco, sumo de ananás. 5€ / 8€ conforme a marca.', 'Rum, coconut cream, pineapple juice. €5 / €8 by brand.', 5.00, 24, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Paloma', 'Paloma', 'Tequila, refrigerante de toranja, sumo de limão. 5€ / 7€ conforme a marca.', 'Tequila, grapefruit soda, lemon juice. €5 / €7 by brand.', 5.00, 25, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Margarita', 'Margarita', 'Tequila, Cointreau, sumo de limão. 5€ / 7€ conforme a marca.', 'Tequila, Cointreau, lemon juice. €5 / €7 by brand.', 5.00, 26, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Tequila Sunrise', 'Tequila Sunrise', 'Tequila, sumo de laranja, grenadine. 5€ / 7€ conforme a marca.', 'Tequila, orange juice, grenadine. €5 / €7 by brand.', 5.00, 27, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Caipirinha', 'Caipirinha', 'Cachaça, lima, açúcar.', 'Cachaça, lime, sugar.', 5.00, 28, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Batida', 'Batida', 'Cachaça, fruta, leite condensado.', 'Cachaça, fruit, condensed milk.', 5.00, 29, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Cocktails' limit 1), 'Caipiroska', 'Caipiroska', 'Vodka, lima, açúcar.', 'Vodka, lime, sugar.', 5.00, 30, true);

-- Destilados
insert into public.categories (name_pt, name_en, sort_order, is_active) values ('Destilados', 'Spirits', 18, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Bacardi Carta Blanca', 'Bacardi Carta Blanca', 'Rum.', 'Rum.', 5.00, 1, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Bacardi Spiced', 'Bacardi Spiced', 'Rum.', 'Rum.', 6.00, 2, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Bacardi Gran Reserva', 'Bacardi Gran Reserva', 'Rum.', 'Rum.', 9.00, 3, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Macieira', 'Macieira', 'Brandy / aguardente.', 'Brandy.', 4.00, 4, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Croft', 'Croft', 'Brandy / aguardente.', 'Brandy.', 4.00, 5, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), '1920', '1920', 'Brandy / aguardente.', 'Brandy.', 4.00, 6, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'CRF Reserva', 'CRF Reserva', 'Brandy / aguardente.', 'Brandy.', 5.00, 7, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), '3 Sombreros', '3 Sombreros', 'Tequila.', 'Tequila.', 5.00, 8, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'José Cuervo', 'José Cuervo', 'Tequila.', 'Tequila.', 7.00, 9, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Eristoff', 'Eristoff', 'Vodka.', 'Vodka.', 5.00, 10, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Eristoff Black', 'Eristoff Black', 'Vodka.', 'Vodka.', 5.00, 11, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Absolut', 'Absolut', 'Vodka.', 'Vodka.', 7.00, 12, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Smirnoff', 'Smirnoff', 'Vodka.', 'Vodka.', 7.00, 13, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), '51', '51', 'Cachaça.', 'Cachaça.', 4.00, 14, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Velho Barreiro', 'Velho Barreiro', 'Cachaça.', 'Cachaça.', 4.00, 15, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Cutty Sark', 'Cutty Sark', 'Whisky.', 'Whisky.', 5.00, 16, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'JB', 'JB', 'Whisky.', 'Whisky.', 5.00, 17, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Ballantines', 'Ballantine''s', 'Whisky.', 'Whisky.', 6.00, 18, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Jameson', 'Jameson', 'Whisky.', 'Whiskey.', 6.00, 19, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Jack Daniels', 'Jack Daniel''s', 'Whisky.', 'Whiskey.', 8.00, 20, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Johnnie Walker Black Label', 'Johnnie Walker Black Label', 'Whisky.', 'Whisky.', 9.00, 21, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Cardhu', 'Cardhu', 'Whisky.', 'Whisky.', 10.00, 22, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Chivas Regal', 'Chivas Regal', 'Whisky.', 'Whisky.', 10.00, 23, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Dimple Golden Selection', 'Dimple Golden Selection', 'Whisky.', 'Whisky.', 11.00, 24, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Old Parr', 'Old Parr', 'Whisky.', 'Whisky.', 12.00, 25, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Gordon''s', 'Gordon''s', 'Gin.', 'Gin.', 6.00, 26, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Bombay', 'Bombay', 'Gin.', 'Gin.', 6.00, 27, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Tanqueray', 'Tanqueray', 'Gin.', 'Gin.', 7.00, 28, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Bulldog', 'Bulldog', 'Gin.', 'Gin.', 9.00, 29, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Nordés', 'Nordés', 'Gin.', 'Gin.', 9.00, 30, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Hendrick''s', 'Hendrick''s', 'Gin.', 'Gin.', 9.00, 31, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Martini / Martini Bianco', 'Martini / Martini Bianco', '', '', 5.00, 32, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Licor Beirão / Amêndoa Amarga / Safari', 'Licor Beirão / Bitter Almond / Safari', '', '', 4.00, 33, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Absinto', 'Absinthe', '', '', 4.00, 34, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Baileys / Macieira Cream', 'Baileys / Macieira Cream', '', '', 4.00, 35, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Malibu', 'Malibu', '', '', 4.00, 36, true);
insert into public.products (category_id, name_pt, name_en, description_pt, description_en, price, sort_order, is_active) values ((select id from public.categories where name_pt = 'Destilados' limit 1), 'Aperol', 'Aperol', '', '', 4.00, 37, true);

commit;

-- Total: 18 categorias, 243 produtos.